name: Default branch checks

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Default branch checks
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle - Check everything compiles and verify snapshots
        run: ./gradlew ktlintCheck clean buildRelease snapshot-test:verifyPaparazziDebug

      - name: Upload snapshot failure deltas
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: snapshot-failure-deltas
          path: snapshot-test/build/paparazzi/failures/delta-*.png
